# TLS
# This adds certificates
- type: replace
  path: /instance_groups/name=Community-VMR/properties/cert_pem?
  value: ((solace_cert.certificate))
- type: replace
  path: /instance_groups/name=Community-VMR/properties/private_key_pem?
  value: ((solace_cert.private_key))
- type: replace
  path: /instance_groups/name=Community-VMR/properties/tls_config/value
  value: enabled
- type: replace
  path: /instance_groups/name=Community-VMR/properties/tls_config/selected_option?/broker_validate_cert_disabled?
  value: ((broker_validate_cert_disabled))
- type: replace
  path: /instance_groups/name=Community-VMR/properties/tls_config/selected_option?/rsa_server_cert/private_key_pem?
  value: ((solace_cert.private_key))
- type: replace
  path: /instance_groups/name=Community-VMR/properties/tls_config/selected_option?/rsa_server_cert/cert_pem?
  value: ((solace_cert.certificate))
- type: replace
  path: /instance_groups/name=Shared-VMR/properties/cert_pem?
  value: ((solace_cert.certificate))
- type: replace
  path: /instance_groups/name=Shared-VMR/properties/private_key_pem?
  value: ((solace_cert.private_key))
- type: replace
  path: /instance_groups/name=Shared-VMR/properties/tls_config/value
  value: enabled
- type: replace
  path: /instance_groups/name=Shared-VMR/properties/tls_config/selected_option?/broker_validate_cert_disabled?
  value: ((broker_validate_cert_disabled))
- type: replace
  path: /instance_groups/name=Shared-VMR/properties/tls_config/selected_option?/rsa_server_cert/private_key_pem?
  value: ((solace_cert.private_key))
- type: replace
  path: /instance_groups/name=Shared-VMR/properties/tls_config/selected_option?/rsa_server_cert/cert_pem?
  value: ((solace_cert.certificate))
- type: replace
  path: /instance_groups/name=Medium-HA-VMR/properties/cert_pem?
  value: ((solace_cert.certificate))
- type: replace
  path: /instance_groups/name=Medium-HA-VMR/properties/private_key_pem?
  value: ((solace_cert.private_key))
- type: replace
  path: /instance_groups/name=Medium-HA-VMR/properties/tls_config/value
  value: enabled
- type: replace
  path: /instance_groups/name=Medium-HA-VMR/properties/tls_config/selected_option?/broker_validate_cert_disabled?
  value: ((broker_validate_cert_disabled))
- type: replace
  path: /instance_groups/name=Medium-HA-VMR/properties/tls_config/selected_option?/rsa_server_cert/private_key_pem?
  value: ((solace_cert.private_key))
- type: replace
  path: /instance_groups/name=Medium-HA-VMR/properties/tls_config/selected_option?/rsa_server_cert/cert_pem?
  value: ((solace_cert.certificate))
- type: replace
  path: /instance_groups/name=Large-VMR/properties/cert_pem?
  value: ((solace_cert.certificate))
- type: replace
  path: /instance_groups/name=Large-VMR/properties/private_key_pem?
  value: ((solace_cert.private_key))
- type: replace
  path: /instance_groups/name=Large-VMR/properties/tls_config/value
  value: enabled
- type: replace
  path: /instance_groups/name=Large-VMR/properties/tls_config/selected_option?/broker_validate_cert_disabled?
  value: ((broker_validate_cert_disabled))
- type: replace
  path: /instance_groups/name=Large-VMR/properties/tls_config/selected_option?/rsa_server_cert/private_key_pem?
  value: ((solace_cert.private_key))
- type: replace
  path: /instance_groups/name=Large-VMR/properties/tls_config/selected_option?/rsa_server_cert/cert_pem?
  value: ((solace_cert.certificate))
- type: replace
  path: /instance_groups/name=Large-HA-VMR/properties/cert_pem?
  value: ((solace_cert.certificate))
- type: replace
  path: /instance_groups/name=Large-HA-VMR/properties/private_key_pem?
  value: ((solace_cert.private_key))
- type: replace
  path: /instance_groups/name=Large-HA-VMR/properties/tls_config/value
  value: enabled
- type: replace
  path: /instance_groups/name=Large-HA-VMR/properties/tls_config/selected_option?/broker_validate_cert_disabled?
  value: ((broker_validate_cert_disabled))
- type: replace
  path: /instance_groups/name=Large-HA-VMR/properties/tls_config/selected_option?/rsa_server_cert/private_key_pem?
  value: ((solace_cert.private_key))
- type: replace
  path: /instance_groups/name=Large-HA-VMR/properties/tls_config/selected_option?/rsa_server_cert/cert_pem?
  value: ((solace_cert.certificate))
- type: replace
  path: /instance_groups/name=deploy-all/properties/tls_config/value
  value: enabled
- type: replace
  path: /instance_groups/name=deploy-all/properties/tls_config/selected_option?/broker_validate_cert_disabled?
  value: ((broker_validate_cert_disabled))
- type: replace
  path: /instance_groups/name=deploy-all/properties/tls_config/selected_option?/rsa_server_cert/private_key_pem?
  value: ((solace_cert.private_key))
- type: replace
  path: /instance_groups/name=deploy-all/properties/tls_config/selected_option?/rsa_server_cert/cert_pem?
  value: ((solace_cert.certificate))
