- type: replace
  path: /instance_groups/name=Shared/properties/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=Large/properties/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=Medium-HA/properties/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=Large-HA/properties/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=deploy-all/properties/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=tests/properties/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=delete-all/properties/application_access_auth_scheme/value
  value: ldap_server

