- type: replace
  path: /instance_groups/name=enterprise-shared/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=enterprise-large/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=enterprise-medium-ha/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=enterprise-large-ha/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=enterprise-plan-5/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=enterprise-plan-6/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=standard-medium/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=standard-medium-ha/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=standard-plan-3/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=standard-plan-4/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
  
# On demand catalog
- type: replace
  path: /instance_groups/name=management/jobs/name=broker/properties/service_catalog/plans/pool_name=enterprise-shared/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=management/jobs/name=broker/properties/service_catalog/plans/pool_name=enterprise-large/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=management/jobs/name=broker/properties/service_catalog/plans/pool_name=enterprise-medium-ha/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=management/jobs/name=broker/properties/service_catalog/plans/pool_name=enterprise-large-ha/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=management/jobs/name=broker/properties/service_catalog/plans/pool_name=enterprise-plan-5/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=management/jobs/name=broker/properties/service_catalog/plans/pool_name=enterprise-plan-6/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=management/jobs/name=broker/properties/service_catalog/plans/pool_name=standard-medium/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=management/jobs/name=broker/properties/service_catalog/plans/pool_name=standard-medium-ha/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=management/jobs/name=broker/properties/service_catalog/plans/pool_name=standard-plan-3/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=management/jobs/name=broker/properties/service_catalog/plans/pool_name=standard-plan-4/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
  
- type: replace
  path: /instance_groups/name=management/jobs/name=deploy-all/properties/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=management/jobs/name=tests/properties/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=management/jobs/name=delete-all/properties/application_access_auth_scheme/value
  value: ldap_server

